version: "3"

services:

  #mysql service
  db:
    image: mysql:8.0
    volumes:
      - /db_data:/var/lib/mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_name
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  #backend service
  backend:
    image: backend
    container_name: spring-boot
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/db_name
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
      MYSQL_PORT: 3306
    ports:
      - "8080:8080"

    #frontend service
  frontend:
    image: frontend
    container_name: react-app
    ports:
      - "3000:3000"

  volumes:
    db_data:

  networks:
    network:


